# Generated by Django 5.2.8 on 2025-11-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('honeymoon', 'Honeymoon'), ('family', 'Family'), ('solo', 'Solo'), ('friends', 'Friends')], default='family', max_length=20),
        ),
    ]
