# Generated by Django 5.2.8 on 2025-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminuser_remove_destination_slug_destination_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
        migrations.AddField(
            model_name='package',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel_3star', '3 Star Hotel'), ('hotel_4star', '4 Star Hotel'), ('hotel_5star', '5 Star Hotel'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('villa', 'Private Villa')], default='hotel_3star', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='packages', to='core.destination'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='meals_plan',
            field=models.CharField(choices=[('breakfast', 'Breakfast Only'), ('breakfast_dinner', 'Breakfast & Dinner'), ('all_meals', 'All Meals'), ('no_meals', 'No Meals')], default='breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='transportation_mode',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus (AC Volvo)'), ('car', 'Private Car'), ('mixed', 'Mixed Mode')], default='car', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='url_name',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Name (Slug)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed itinerary and inclusions'),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief summary for cards'),
        ),
    ]
