# Generated by Django 5.2.8 on 2025-12-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_package_slug_package_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for distance calculations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for distance calculations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='available_for_booking',
            field=models.BooleanField(default=True, help_text='Enable/disable customer booking'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_preplanned',
            field=models.BooleanField(default=False, help_text='Admin-created pre-planned package'),
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, help_text='Day-by-day itinerary with places and activities'),
        ),
    ]
