# Generated by Django 5.2.8 on 2026-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_destination_latitude_destination_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='target_audience',
            field=models.CharField(choices=[('single', 'Single'), ('couple', 'Couples'), ('family', 'Family'), ('friends', 'Friends')], default='family', help_text='Recommended audience for this package', max_length=20),
        ),
    ]
