# Generated by Django 6.0.1 on 2026-03-31 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_package_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gouser',
            name='data_analytics',
        ),
        migrations.RemoveField(
            model_name='gouser',
            name='show_travel_history',
        ),
        migrations.AddField(
            model_name='gouser',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be between 4 and 25 characters, lowercase only, spaces allowed.', regex='^[a-z ]{4,25}$')]),
        ),
    ]
