# Generated by Django 6.0.1 on 2026-04-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_gouser_data_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('luxury', 'Luxury'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='emi_installments',
            field=models.PositiveIntegerField(default=0, help_text='Number of EMI installments'),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total after EMI interest if applicable', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('emi', 'EMI Option')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='travelers_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Extra message from user', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed (Awaiting Payment)'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original package cost', max_digits=12),
        ),
    ]
