# Generated by Django 6.0.1 on 2026-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_booking_category_booking_emi_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount paid by customer', max_digits=12),
        ),
    ]
