# Generated by Django 5.2.8 on 2025-11-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('travel_style', models.CharField(blank=True, choices=[('budget', 'Budget Traveler'), ('comfort', 'Comfort Seeker'), ('luxury', 'Luxury Traveler')], max_length=20, null=True)),
                ('accommodation_preference', models.CharField(blank=True, choices=[('hotel', 'Hotels'), ('resort', 'Resorts'), ('homestay', 'Homestays'), ('hostel', 'Hostels')], max_length=20, null=True)),
                ('budget_range', models.CharField(blank=True, choices=[('low', '₹10K - ₹25K'), ('medium', '₹25K - ₹50K'), ('high', '₹50K - ₹1L'), ('premium', '₹1L+')], max_length=20, null=True)),
                ('travel_companions', models.CharField(blank=True, max_length=20, null=True)),
                ('travel_interests', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
