# Generated by Django 5.2.8 on 2025-12-16 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_destination_latitude_destination_longitude_and_more'),
        ('customers', '0003_remove_itineraryactivity_itinerary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tripplan',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin feedback or revision notes', null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='converted_to_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_trip_plan', to='core.package'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='trip_plans', to='core.destination'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, admin can make this plan available for all customers'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='meals',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast Only'), ('breakfast_dinner', 'Breakfast & Dinner'), ('all_meals', 'All Meals'), ('no_meals', 'No Meals')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='number_of_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of days for the trip'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trip_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('customer_review', 'Customer Reviewing Changes')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='transportation',
            field=models.CharField(blank=True, choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus (AC Volvo)'), ('car', 'Private Car'), ('mixed', 'Mixed Mode')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='accommodation',
            field=models.CharField(blank=True, choices=[('hotel_3star', '3 Star Hotel'), ('hotel_4star', '4 Star Hotel'), ('hotel_5star', '5 Star Hotel'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('villa', 'Private Villa'), ('hostel', 'Hostel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_trip_plans', to='core.destination'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, help_text='Array of day objects with activities and destinations'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='start_date',
            field=models.DateField(blank=True, help_text='Selected after plan approval', null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('budget', 'Budget Friendly'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=50, null=True),
        ),
    ]
