# Generated by Django 5.2.8 on 2025-12-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_tripplan_options_tripplan_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='end_location',
            field=models.CharField(blank=True, help_text='Ending point of the trip', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='start_location',
            field=models.CharField(blank=True, help_text='Starting point of the trip', max_length=255, null=True),
        ),
    ]
